package mapper

import (
	"strings"

	c2qtypes "github.com/Inoriol/comquad/compose2quadlet/internal/types"
)

var knownContainerDirectives = map[string]bool{
	"AddCapability=":         true,
	"AddDevice=":             true,
	"AddHost=":               true,
	"Annotation=":            true,
	"AppArmor=":              true,
	"AutoUpdate=":            true,
	"ContainersConfModule=":  true,
	"CgroupsMode=":           true,
	"ContainerName=":         true,
	"DNS=":                   true,
	"DNSOption=":             true,
	"DNSSearch=":             true,
	"DropCapability=":        true,
	"Entrypoint=":            true,
	"Environment=":           true,
	"EnvironmentFile=":       true,
	"EnvironmentHost=":       true,
	"Exec=":                  true,
	"ExposeHostPort=":        true,
	"GIDMap=":                true,
	"GlobalArgs=":            true,
	"Group=":                 true,
	"GroupAdd=":              true,
	"HealthCmd=":             true,
	"HealthInterval=":        true,
	"HealthLogDestination=":   true,
	"HealthMaxLogCount=":     true,
	"HealthMaxLogSize=":      true,
	"HealthOnFailure=":       true,
	"HealthRetries=":         true,
	"HealthStartPeriod=":     true,
	"HealthStartupCmd=":      true,
	"HealthStartupInterval=": true,
	"HealthStartupRetries=":  true,
	"HealthStartupSuccess=":  true,
	"HealthStartupTimeout=":  true,
	"HealthTimeout=":         true,
	"HostName=":              true,
	"HttpProxy=":             true,
	"IP=":                    true,
	"IP6=":                   true,
	"Image=":                 true,
	"ImageVolume=":           true,
	"Internal=":              true,
	"Label=":                 true,
	"LogDriver=":             true,
	"LogOpt=":                true,
	"Mask=":                  true,
	"Memory=":                true,
	"Mount=":                 true,
	"Network=":               true,
	"NetworkAlias=":          true,
	"NoNewPrivileges=":       true,
	"Notify=":                true,
	"Pod=":                   true,
	"PodmanArgs=":            true,
	"PublishPort=":           true,
	"Pull=":                  true,
	"ReadOnly=":              true,
	"ReadOnlyTmpfs=":         true,
	"ReloadCmd=":             true,
	"ReloadSignal=":          true,
	"Retry=":                 true,
	"RetryDelay=":            true,
	"Rootfs=":                true,
	"RunInit=":               true,
	"SecurityLabelDisable=":  true,
	"SecurityLabelFileType=": true,
	"SecurityLabelLevel=":    true,
	"SecurityLabelNested=":   true,
	"SecurityLabelType=":     true,
	"SeccompProfile=":        true,
	"ServiceName=":           true,
	"ShmSize=":               true,
	"StartWithPod=":          true,
	"StopSignal=":            true,
	"StopTimeout=":           true,
	"SubGIDMap=":             true,
	"SubUIDMap=":             true,
	"Sysctl=":                true,
	"Timezone=":              true,
	"Tmpfs=":                 true,
	"UIDMap=":                true,
	"Umask=":                 true,
	"Unmask=":                true,
	"User=":                  true,
	"UserNS=":                true,
	"Volume=":                true,
	"WorkingDir=":            true,
}

var knownNetworkDirectives = map[string]bool{
	"ContainersConfModule=": true,
	"DisableDNS=":           true,
	"Driver=":               true,
	"Gateway=":              true,
	"IPAMDriver=":           true,
	"IPRange=":              true,
	"Internal=":             true,
	"InterfaceName=":        true,
	"IPv6=":                 true,
	"Label=":                true,
	"NetworkDeleteOnStop=":  true,
	"NetworkName=":          true,
	"Options=":              true,
	"Subnet=":               true,
}

var knownVolumeDirectives = map[string]bool{
	"ContainersConfModule=": true,
	"Copy=":                 true,
	"Device=":               true,
	"Driver=":               true,
	"GID=":                  true,
	"Group=":                true,
	"Image=":                true,
	"Label=":                true,
	"Options=":              true,
	"Type=":                 true,
	"UID=":                  true,
	"User=":                 true,
	"VolumeName=":           true,
}

var knownImageDirectives = map[string]bool{
	"AllTags=":              true,
	"Arch=":                 true,
	"AuthFile=":             true,
	"CertDir=":              true,
	"ContainersConfModule=": true,
	"Creds=":                true,
	"DecryptionKey=":        true,
	"Image=":                true,
	"ImageTag=":             true,
	"OS=":                   true,
	"Policy=":               true,
	"Retry=":                true,
	"RetryDelay=":           true,
	"TLSVerify=":            true,
	"Variant=":              true,
}

var knownBuildDirectives = map[string]bool{
	"Annotation=":           true,
	"Arch=":                 true,
	"AuthFile=":             true,
	"BuildArg=":             true,
	"ContainersConfModule=": true,
	"DNS=":                  true,
	"DNSOption=":            true,
	"DNSSearch=":            true,
	"Environment=":          true,
	"File=":                 true,
	"ForceRM=":              true,
	"ImageTag=":             true,
	"Label=":                true,
	"Network=":              true,
	"PodmanArgs=":           true,
	"Pull=":                 true,
	"Retry=":                true,
	"RetryDelay=":           true,
	"Secret=":               true,
	"SetWorkingDirectory=":  true,
	"TLSVerify=":            true,
	"Target=":               true,
	"Variant=":              true,
	"Volume=":               true,
}

var knownServiceDirectives = map[string]bool{
	"AllowedCPUs=":         true,
	"AllowedMemoryNodes=":  true,
	"CPUAccounting=":       true,
	"CPUQuota=":            true,
	"CPUQuotaPeriodSec=":   true,
	"CPUWeight=":           true,
	"Delegate=":            true,
	"DeviceAllow=":         true,
	"DevicePolicy=":        true,
	"Environment=":         true,
	"ExecStart=":           true,
	"ExecStartPre=":        true,
	"ExecStartPost=":       true,
	"ExecStop=":            true,
	"ExecStopPost=":        true,
	"IOAccounting=":        true,
	"IODeviceWeight=":      true,
	"IOReadBandwidthMax=":  true,
	"IOReadIOPSMax=":       true,
	"IOWeight=":            true,
	"IOWriteBandwidthMax=": true,
	"IOWriteIOPSMax=":      true,
	"IPAccounting=":        true,
	"LimitAS=":             true,
	"LimitCORE=":           true,
	"LimitCPU=":            true,
	"LimitDATA=":           true,
	"LimitFSIZE=":          true,
	"LimitLOCKS=":          true,
	"LimitMEMLOCK=":        true,
	"LimitMSGQUEUE=":       true,
	"LimitNICE=":           true,
	"LimitNOFILE=":         true,
	"LimitNPROC=":          true,
	"LimitRSS=":             true,
	"LimitRTPRIO=":         true,
	"LimitRTTIME=":         true,
	"LimitSIGPENDING=":     true,
	"LimitSTACK=":          true,
	"MemoryAccounting=":    true,
	"MemoryHigh=":          true,
	"MemoryLow=":           true,
	"MemoryMax=":           true,
	"MemoryMin=":           true,
	"MemorySwapMax=":       true,
	"OOMPolicy=":           true,
	"OOMScoreAdjust=":      true,
	"Restart=":             true,
	"RestartSec=":          true,
	"RuntimeMaxSec=":       true,
	"Slice=":               true,
	"StandardError=":       true,
	"StandardOutput=":      true,
	"StartLimitBurst=":     true,
	"StartLimitIntervalSec=": true,
	"SyslogIdentifier=":     true,
	"TasksAccounting=":      true,
	"TasksMax=":             true,
	"TimeoutStartSec=":      true,
	"TimeoutStopSec=":       true,
	"Type=":                 true,
	"WatchdogSec=":          true,
}

var knownUnitDirectives = map[string]bool{
	"After=":            true,
	"Alias=":            true,
	"AllowIsolate=":     true,
	"BindsTo=":          true,
	"Before=":           true,
	"ConditionACPower=": true,
	"ConditionArchitecture=": true,
	"ConditionCPUs=":         true,
	"ConditionCapability=":  true,
	"ConditionDirectoryNotEmpty=": true,
	"ConditionEnvironment=":      true,
	"ConditionFileIsExecutable=": true,
	"ConditionFileNotEmpty=":      true,
	"ConditionGroup=":            true,
	"ConditionHost=":             true,
	"ConditionKernelCommandLine=": true,
	"ConditionKernelVersion=":     true,
	"ConditionMemory=":            true,
	"ConditionNeedsUpdate=":       true,
	"ConditionPathExists=":        true,
	"ConditionPathIsDirectory=":   true,
	"ConditionPathIsMountPoint=":  true,
	"ConditionPathIsReadWrite=":   true,
	"ConditionPathIsSymbolicLink=": true,
	"ConditionSecurity=":           true,
	"ConditionUser=":               true,
	"ConditionVirtualization=":     true,
	"Conflicts=":                   true,
	"DefaultDependencies=":         true,
	"Description=":                 true,
	"Documentation=":               true,
	"JoinsNamespaceOf=":            true,
	"OnFailure=":                   true,
	"OnSuccess=":                   true,
	"PartOf=":                      true,
	"PropagatesReloadTo=":          true,
	"PropagatesStopTo=":            true,
	"Requires=":                    true,
	"RequiresMountsFor=":           true,
	"Requisite=":                   true,
	"ReloadPropagatedFrom=":        true,
	"Restart=":                     true,
	"SourcePath=":                  true,
	"Wants=":                       true,
	"WantedBy=":                    true,
}

func isValidDirective(section, key string) bool {
	if !strings.HasSuffix(key, "=") {
		key += "="
	}

	switch section {
	case c2qtypes.SectionContainer:
		return knownContainerDirectives[key]
	case c2qtypes.SectionNetwork:
		return knownNetworkDirectives[key]
	case c2qtypes.SectionVolume:
		return knownVolumeDirectives[key]
	case c2qtypes.SectionImage:
		return knownImageDirectives[key]
	case c2qtypes.SectionBuild:
		return knownBuildDirectives[key]
	case c2qtypes.SectionService:
		return knownServiceDirectives[key]
	case c2qtypes.SectionUnit:
		return knownUnitDirectives[key]
	default:
		return false
	}
}
