FROM comquad-test:latest

RUN dnf install -y \
    cockpit-ws \
    cockpit-bridge \
    cockpit-system \
    cockpit-storaged \
    chromium-headless \
    python3 \
    python3-pip \
    python3-devel \
    gcc \
    openssl-devel \
    libssh-devel \
    && dnf clean all

RUN pip3 install \
    selenium \
    pytest \
    pexpect \
    ssh2-python \
    && rm -rf /root/.cache/pip

COPY cockpit-comquad/test/browser/vm.install /vm.install
RUN chmod +x /vm.install

COPY cockpit-comquad/test/browser/run /run
RUN chmod +x /run

COPY cockpit-comquad/test/browser/test-comquad.py /test-comquad.py

ENV COCKPIT_COMQUAD_PLUGIN=1
