package graft

// Grafter post-processes quadlet files to handle compose fields
// that podlet does not support or supports with known flaws.
type Grafter struct{}

// Process post-processes quadlet file contents generated by the cooker.
// Currently a no-op stub — future handlers in handlers/ will plug gaps
// (e.g. intercepting build: blocks that podlet handles imperfectly,
// post-processing secrets, etc.).
//
// build: blocks are passed through to podlet unchanged.
// See handlers/ for planned coverage.
func (g *Grafter) Process(files map[string]string) (map[string]string, error) {
	return files, nil
}
