package graft

import (
	"github.com/Inoriol/comquad/internal/graft/handlers"
	"github.com/Inoriol/comquad/internal/preprocess"
)

// Grafter post-processes quadlet files to handle compose fields
// that podlet does not support or supports with known flaws.
type Grafter struct {
	ProjectName    string
	SecretsDir     string
	DryRun         bool
	SELinuxEnabled bool
}

// Process post-processes quadlet file contents generated by the cooker.
func (g *Grafter) Process(
	files map[string]string,
	services map[string]preprocess.ServiceImageSpec,
	secretDefs map[string]preprocess.SecretDef,
	serviceSecretRefs preprocess.ServiceSecretRefs,
) map[string]string {
	if len(secretDefs) > 0 {
		files = handlers.SecretHandler(files, g.ProjectName, secretDefs, serviceSecretRefs, g.SecretsDir, g.DryRun, g.SELinuxEnabled)
	}
	files = handlers.ImageQuadletHandler(files, g.ProjectName, services)
	return files
}
