package graft

import (
	"github.com/Inoriol/comquad/internal/graft/handlers"
	"github.com/Inoriol/comquad/internal/preprocess"
)

// Grafter post-processes quadlet files to handle compose fields
// that podlet does not support or supports with known flaws.
type Grafter struct {
	ProjectName string
}

// Process post-processes quadlet file contents generated by the cooker.
//
// Currently the only handler creates .image quadlet files for every
// .container, moving image-related directives out of the container
// so systemd can manage image pulls as separate units.
func (g *Grafter) Process(files map[string]string, services map[string]preprocess.ServiceImageSpec) map[string]string {
	return handlers.ImageQuadletHandler(files, g.ProjectName, services)
}
